config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  #good job on nested routes
  devise_for :users

  resources :jobs do
    member do
      post :cover
    end
  end

  resources :job_types do
    member do
      get :training_module
      get :take_quiz    
      post :submit_quiz 
      post :complete_training
    end
  end

  resources :users, only: [:show, :edit, :update]

end

app/controllers/job_types_controller.rb
# app/controllers/job_types_controller.rb

class JobTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job_type, only: [:show, :edit, :training_module, :take_quiz, :submit_quiz]

  def index
    @job_types = JobType.all
  end

  def show
    # If user has the profession, show a summary
    # If not, show a "Start Training" button
  end

  # Some of these can go in the model

  def training_module
    @learning_module = @job_type.learning_module
    # Show full module
  end

  def take_quiz
    redirect_to @job_type, notice: "You have already completed this training." and return if current_user.has_profession?(@job_type)

    @learning_module = @job_type.learning_module
    @questions = @learning_module.quiz_questions.includes(:quiz_options)
  end

  def submit_quiz
    @learning_module = @job_type.learning_module
    @questions = @learning_module.quiz_questions

    correct_count = 0
    @questions.each do |question|
      selected_option_id = params[:quiz][question.id.to_s].to_i
      selected_option = question.quiz_options.find(selected_option_id)
      correct_count += 1 if selected_option.correct
    end

    passing_score = (@questions.count * 0.75).ceil

    if correct_count >= passing_score
      current_user.user_job_types.find_or_create_by!(job_type: @job_type)
      redirect_to @job_type, notice: "Congratulations! You've completed the training and earned the #{@job_type.title} profession."
    else
      redirect_to take_quiz_job_type_path(@job_type), alert: "You scored #{correct_count}/#{@questions.count}. Review the material and try again."
    end
  end

  # Other actions (new, create, edit, update, destroy) if needed
  # ...

  private

  def set_job_type
    @job_type = JobType.find(params[:id])
  end
end

app/views/job_types/_form.html.erb
<%= simple_form_for(@job_type) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :training_module %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/job_types/_job_type.html.erb
<div id="<%= dom_id job_type %>">
  <p>
    <strong>Title:</strong>
    <%= job_type.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= job_type.description %>
  </p>

  <p>
    <strong>Training module:</strong>
    <%= job_type.training_module %>
  </p>

</div>

app/views/job_types/edit.html.erb
<h1>Editing job type</h1>

<%= render "form", job_type: @job_type %>

<br>

<div>
  <%= link_to "Show this job type", @job_type %> |
  <%= link_to "Back to job types", job_types_path %>
</div>

app/views/job_types/index.html.erb
<h1>Job Types</h1>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @job_types.each do |job_type| %>
      <tr>
        <td><%= job_type.title %></td>
        <td><%= truncate(job_type.description, length: 100) %></td>
        <td><%= link_to 'View Details', job_type_path(job_type), class: 'btn btn-info' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/job_types/new.html.erb
<h1>New job type</h1>

<%= render "form", job_type: @job_type %>

<br>

<div>
  <%= link_to "Back to job types", job_types_path %>
</div>

app/views/job_types/show.html.erb
<div class="container">
  <h1><%= @job_type.title %></h1>
<p><%= markdown(@job_type.description) %></p>

<% if current_user.has_profession?(@job_type) %>
  <h2>Summary</h2>
  <div class="job-content">
    <%= markdown(@job_type.learning_module.content) %>
  </div>
<% else %>
  <p>You have not earned this credential yet.</p>
  <%= link_to 'Start Training', training_module_job_type_path(@job_type), class: 'btn btn-primary' %>
<% end %>

</div>

app/views/job_types/take_quiz.html.erb
<h1><%= @job_type.title %> Quiz</h1>
<p>Complete the quiz below to earn the profession credential!</p>

<div data-controller="quiz">
  <%= form_with url: submit_quiz_job_type_path(@job_type), method: :post, local: true do %>
  <% @questions.each do |question| %>
    <div class="mb-3">
      <strong><%= question.question %></strong><br>
      <% question.quiz_options.each do |option| %>
        <div class="form-check">
          <%= radio_button_tag "quiz[#{question.id}]", option.id, false, id: "option_#{option.id}", class: "form-check-input" %>
          <%= label_tag "option_#{option.id}", option.option_text, class: "form-check-label" %>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= submit_tag "Submit Quiz", class: "btn btn-success" %>
<% end %>
</div>

app/views/job_types/training_module.html.erb
<div class="container">
  <h1><%= @job_type.title %> - Training Module</h1>
<% if @learning_module.present? %>
  <%= simple_format(@learning_module.content) %>
  <% if current_user.has_profession?(@job_type) %>
    <p>You have already earned this profession. Below is the training content for reference.</p>
  <% else %>
    <%= link_to 'Take Quiz', take_quiz_job_type_path(@job_type), class: 'btn btn-success mt-4' %>
  <% end %>
<% else %>
  <p>No training module available for this job type yet.</p>
<% end %>


</div>