config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  #good job on nested routes
  devise_for :users

  resources :jobs do
    member do
      post :cover
    end
  end

  resources :job_types do
    member do
      get :training_module
      get :take_quiz    
      post :submit_quiz 
      post :complete_training
    end
  end

  resources :users, only: [:show, :edit, :update]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :citext           default(""), not null
#  encrypted_password     :string           default(""), not null
#  location               :string
#  name                   :citext
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_name                  (name) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posted_jobs, class_name: 'Job', foreign_key: 'opener_id', dependent: :destroy
  has_many :covered_jobs, class_name: 'Job', foreign_key: 'cover_id'

  has_many :user_job_types, dependent: :destroy
  has_many :job_types, through: :user_job_types
  has_many :user_trainings, dependent: :destroy
  has_many :completed_job_types, through: :user_trainings, source: :job_type

  has_one_attached :profile_picture

  validates :name, presence: true, uniqueness: true

  validate :acceptable_image


  def acceptable_image
    return unless profile_picture.attached?

    unless profile_picture.byte_size <= 1.megabyte
      errors.add(:profile_picture, "is too big")
    end

    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(profile_picture.content_type)
      errors.add(:profile_picture, "must be a JPEG or PNG")
    end
  end

  def has_profession?(job_type)
    job_types.exists?(job_type.id)
  end

  def eligible_jobs
    Job.where(cover_id: nil, job_type_id: job_types.ids)
  end

  def ineligible_jobs
    Job.where(cover_id: nil).where.not(job_type_id: job_types.ids)
  end 
  
  after_create :send_welcome_email



  private

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_later
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show]
  before_action :set_current_user, only: [:edit, :update]
  # I can remove the :correct_user before_action if @user is always current_user

  def show
    @user = User.find(params[:id])
    @posted_jobs = @user.posted_jobs.order(shift_date: :desc) # Fetch and order the user's posted jobs
  end

  def edit
    # @user is set by set_current_user (current_user)
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Profile updated successfully.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :location, :profile_picture)
  end
end

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for @user, html: { multipart: true } do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :profile_picture %><br />
    <% if @user.profile_picture.attached? %>
    <%= image_tag(@user.profile_picture, class: 'img-thumbnail') %>
  
  <br />
    <% end %>
    <%= f.file_field :profile_picture %>
  </div>

  <div class="actions">
    <%= f.submit 'Update Profile', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="card mb-4">
        <div class="card-body text-center">
          <% if @user.profile_picture.attached? %>
            <%= image_tag @user.profile_picture, class: 'profile-image mb-2', alt: @user.name, width: 150, height: 150 %>
          <% else %>
            <%= image_tag 'default_avatar.png', class: 'profile-image mb-2', alt: 'Default Avatar', width: 150, height: 150 %>
          <% end %>
          <h5><%= @user.name %></h5>
          <p class="text-muted"><%= @user.location %></p>
          <p><strong>Professions:</strong> <%= @user.job_types.map(&:title).join(', ') %></p>
          <%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-primary btn-sm mt-2' %>
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <h2>My Posted Jobs</h2>
      <% if @posted_jobs.any? %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Title</th>
              <th>Company</th>
              <th>Location</th>
              <th>Date</th>
              <th>Time</th>
              <th>Covered By</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @posted_jobs.each do |job| %>
              <tr>
                <td><%= link_to job.job_type.title, job_path(job) %></td>
                <td><%= job.company_name.present? ? job.company_name : 'N/A' %></td>
                <td><%= job.location_address.present? ? job.location_address : 'N/A' %></td>
                <td><%= job.shift_date.strftime("%B %d, %Y") %></td>
                <td><%= job.shift_started_at.strftime("%I:%M %p") %> - <%= job.shift_ended_at.strftime("%I:%M %p") %></td>
                <td>
                  <% if job.cover.present? %>
                    <%= link_to job.cover.name, user_path(job.cover) %>
                  <% else %>
                    <span class="text-muted">Not Covered</span>
                  <% end %>
                </td>
                <td>
                  <%= link_to 'Edit', edit_job_path(job), class: 'btn btn-primary btn-sm' %>
                  <%= link_to 'Delete', job_path(job), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @posted_jobs %>
      <% else %>
        <p>You have not posted any jobs.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>